name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      VITE_OPENAI_API_KEY: ${{ secrets.VITE_OPENAI_API_KEY }}
      VITE_GROQ_API_KEY: ${{ secrets.VITE_GROQ_API_KEY }}
      VITE_GROK_API_KEY: ${{ secrets.VITE_GROK_API_KEY }}
      VITE_ADMIN_PASSWORD: ${{ secrets.VITE_ADMIN_PASSWORD }}
      VITE_PORT: ${{ vars.VITE_PORT }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install || true

      - name: Build the application
        run: npm run build || true

      - name: Restart the application
        run: |
          pm2 restart quizzy || pm2 start <entry_file.js> --name quizzy || true