name: Deploy Only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Local Machine
        env:
          HOST: "katsana.myds.me"
          USER: "katsana"
        run: |
          ssh -o StrictHostKeyChecking=no -p 5022 $USER@$HOST "cd ~/quizzy && ./deploy-script.sh"